config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  match '/forgot-password' => 'password_resets#new', via: :get, as: :new_password_reset
  match '/forgot-password' => 'password_resets#create', via: :post, as: :create_password_reset
  match '/password-resets/:token' => 'password_resets#edit', via: :get, as: :edit_password_reset
  match '/password-resets/:token' => 'password_resets#update', via: :patch, as: :update_password_reset
  match '/change-password' => 'password_updates#edit', via: :get, as: :edit_password
  match '/change-password' => 'password_updates#update', via: :patch, as: :update_password

  match '/sign-in' => 'session#new', via: :get, as: :sign_in
  match '/sign-in' => 'session#create', via: :post, as: :authenticate
  match '/sign-out' => 'session#destroy', via: :get, as: :sign_out

  match '/api/username-uniqueness' => 'api#username_uniqueness', via: :get

  resources :users
  resources :events
  match '/calendar(/:year/:month)' => 'events#index', via: :get, as: :monthly_calendar


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  include SessionHelper

  skip_before_filter :authenticate
  before_filter :get_user, only: [:edit, :update]
  before_filter :validate_user, only: [:edit, :update]
  before_filter :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by_username params[:password_reset][:username].downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
    end
  end

  def edit
  end

  def update
    @user.password = params[:password_reset][:password]
    @user.password_confirmation = params[:password_reset][:password_confirmation]
    if @user.valid? and @user.save
      sign_in @user
      remember @user
      redirect_to :root and return
    end

    flash.now[:alert] = t :error_occurred_processing_last_request
    render :edit
  end

  private

  def get_user
    @user = User.find_by_username params[:username]
  end

  def validate_user
    unless @user and @user.authenticated? :reset, params[:token]
      flash[:alert] = t :error_occurred_during_authentication
      redirect_to new_password_reset_path
    end
  end

  def check_expiration
    if @user.reset_sent_at.advance(hours: 24).past?
      flash[:alert] = t :password_reset_token_expired
      redirect_to new_password_reset_path
    end
  end
end

app/views/password_resets/create.html.slim
p =t :check_your_email

app/views/password_resets/edit.html.slim
h1 =t :password_reset
p =t :choose_a_new_password

=form_for @user, as: :password_reset, url: update_password_reset_path(params[:token]), builder: AngularValidation::FormBuilder do |form|
  =hidden_field_tag :username, @user.username

  .form-group
    =form.label :password
    =form.password_field :password, class: 'form-control', required: 'required'
    =form.ng_messages :password, additional_validators: { required: t('errors.messages.field_is_required') }

  .form-group
    =form.label :password_confirmation
    =form.password_field :password_confirmation, class: 'form-control', required: 'required'
    =form.ng_messages :password_confirmation, additional_validators: { required: t('errors.messages.field_is_required') }

  =form.submit value: t(:continue), class:'btn.btn-default'

app/views/password_resets/new.html.slim
=t :password_reset_instructions

=form_for :password_reset, html: { name: 'password_reset', url: create_password_reset_path, 'submit-on-valid' => '' } do |form|
  .form-group
    =form.label :username
    =form.text_field :username, class: 'form-control', required: 'required'
    ng-messages for="password_reset['password_reset[username]'].$error"
      ng-message when="required"
        =t 'errors.messages.field_is_required'

  =form.submit value: t(:continue), class:'btn.btn-default'