config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  match '/forgot-password' => 'password_resets#new', via: :get, as: :new_password_reset
  match '/forgot-password' => 'password_resets#create', via: :post, as: :create_password_reset
  match '/password-resets/:token' => 'password_resets#edit', via: :get, as: :edit_password_reset
  match '/password-resets/:token' => 'password_resets#update', via: :patch, as: :update_password_reset
  match '/change-password' => 'password_updates#edit', via: :get, as: :edit_password
  match '/change-password' => 'password_updates#update', via: :patch, as: :update_password

  match '/sign-in' => 'session#new', via: :get, as: :sign_in
  match '/sign-in' => 'session#create', via: :post, as: :authenticate
  match '/sign-out' => 'session#destroy', via: :get, as: :sign_out

  match '/api/username-uniqueness' => 'api#username_uniqueness', via: :get

  resources :users
  resources :events
  match '/calendar(/:year/:month)' => 'events#index', via: :get, as: :monthly_calendar


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :authenticate, except: :destroy

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user and user.authenticated?(:password, params[:session][:password])
      sign_in user
      remember user
      redirect_to :root and return
    end

    flash.now[:alert] = t(:incorrect_username_password)
    render :new
  end


  def destroy
    sign_out
    redirect_to :sign_in
  end
end

app/helpers/session_helper.rb
module SessionHelper

  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 1.month.from_now }
    @current_user = user
  end

  def remember(user)
    user.remember
    cookies.signed[:remember_token] = { value: user.remember_token, expires: 1.month.from_now }
  end

  def sign_out
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    @current_user = nil
  end

  def current_user
    @current_user ||= if user_id = cookies.signed[:user_id]
                        user = User.find_by id: user_id
                        user if user and user.authenticated? :remember, cookies.signed[:remember_token]
                      end
  end
end

app/views/session/new.html.slim
.container
  #loginbox.mainbox.col-md-6.col-md-offset-3.col-sm-8.col-sm-offset-2
    .panel.panel-info
      .panel-heading
        .panel-title =t(:sign_in)
      .panel-body

        =form_for :session, html: { id:'loginform', url: sign_in_path, class:'form-horizontal', role: 'form' }, builder: AngularValidation::FormBuilder do |form|
          .input-group
            span.input-group-addon
              i.glyphicon.glyphicon-user
            =form.text_field :username, id:'login-username', class:'form-control', placeholder: t(:username), required: :required
            ng-messages for="session['session[username]'].$error" ng-show=""
              ng-message when="required"
                =t 'errors.messages.field_is_required'

          .input-group
            span.input-group-addon
              i.glyphicon.glyphicon-lock
            =form.password_field :password, class:'form-control', placeholder: t(:password), required: :required
            ng-messages for="session['session[password]'].$error" ng-show=""
              ng-message when="required"
                =t 'errors.messages.field_is_required'

          .input-group
            .form-group
              .col-sm-12.controls
                =form.submit t(:sign_in), class:'btn btn-success'
              =link_to t(:forgot_your_password), new_password_reset_path, class: 'col-sm-12 controls'