config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  match '/forgot-password' => 'password_resets#new', via: :get, as: :new_password_reset
  match '/forgot-password' => 'password_resets#create', via: :post, as: :create_password_reset
  match '/password-resets/:token' => 'password_resets#edit', via: :get, as: :edit_password_reset
  match '/password-resets/:token' => 'password_resets#update', via: :patch, as: :update_password_reset
  match '/change-password' => 'password_updates#edit', via: :get, as: :edit_password
  match '/change-password' => 'password_updates#update', via: :patch, as: :update_password

  match '/sign-in' => 'session#new', via: :get, as: :sign_in
  match '/sign-in' => 'session#create', via: :post, as: :authenticate
  match '/sign-out' => 'session#destroy', via: :get, as: :sign_out

  match '/api/username-uniqueness' => 'api#username_uniqueness', via: :get

  resources :users
  resources :events
  match '/calendar(/:year/:month)' => 'events#index', via: :get, as: :monthly_calendar


end

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to t(:sync), :root, class: 'a navbar-brand'
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        -if current_user
          li
            =link_to t(:blog), '#'
          li
            =link_to t(:calendar), monthly_calendar_path
      ul.nav.navbar-nav.navbar-right
        -if current_user
          li.dropdown
            a.dropdown-toggle aria-expanded='false' data-toggle='dropdown' href='#' role='button'
              span.glyphicon.glyphicon-user aria-hidden='true'
              ="#{current_user.first_name}"
              span.caret
            ul.dropdown-menu role='menu'
              -if current_user.is_admin?
                li
                  =link_to t(:create_user), new_user_path
                li
                  =link_to t(:manage_users), users_path
              li
                a href="#" =t(:profile)
              li
                =link_to t(:change_password), edit_password_path
              li.divider
              li
                =link_to t(:sign_out), :sign_out

app/views/layouts/application.html.slim
html
  head
    title SYNC
    =stylesheet_link_tag    'application', media: 'all'
    =csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
  body
    .header
      =render 'layouts/header'
    .main-body.container ng-app='SyncApp' ng-cloak=''
      -unless flash.empty?
        -flash.each do |key,value|
          div class="#{key}"
            =value
      =yield
    =javascript_include_tag 'application'